config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'tags/index'
  end

  root to: "static_pages#index"

  namespace :api, defaults: { format: :json} do 
    resources :comments, only: [:create, :destroy] 
    resources :questions
    resources :tags, only: [:index, :create]
    resources :answers, only: [:update, :create, :destroy] 
    resources :question_upvotes, only: [:create]
    get 'question_upvotes/', :to => 'question_upvotes#destroy' 
    resources :answer_upvotes, only: [:create]
    get 'answer_upvotes/', :to => 'answer_upvotes#destroy' 
  end
  

  resources :users, only: [:new, :create, :show, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	validates :user_id, :body, :question_id, presence: true 
	belongs_to :author,
	class_name: "User",
	foreign_key: :user_id
	belongs_to :question 
	has_many :comments, as: :commentable 
	has_many :upvotes,
	class_name: "AnswerUpvote",
	foreign_key: :answer_id,
	primary_key: :id 
	has_many :voters, through: :upvotes, source: :user  
end

app/models/answer_upvote.rb
class AnswerUpvote < ActiveRecord::Base
	validates :user_id, :answer_id, :value, presence: true 
	validates :value, inclusion: { in: [-1,1] }
	validates_uniqueness_of :user_id, scope: :answer_id 

	belongs_to :user
	belongs_to :answer 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true 
	belongs_to :user 
	
end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :title, :user_id, presence: true 
	belongs_to :author,
	class_name: "User",
	foreign_key: :user_id, 
	primary_key: :id
	has_many :answers
	has_many :comments, as: :commentable  

	has_many :taggings
	has_many :tags, through: :taggings
	has_many :upvotes,
	class_name: "QuestionUpvote",
	foreign_key: :question_id,
	primary_key: :id 
	has_many :voters, through: :upvotes, source: :user  

	def self.find_by_substring(str)
		Question.limit(5).where("LOWER(title) LIKE '%#{str.downcase}%'")
	end

	def assign_tags(tag_names) 
		tag_names.each {|tag_name| self.tags << Tag.find_or_create_by({name: tag_name})}
	end


end

app/models/question_upvote.rb
class QuestionUpvote < ActiveRecord::Base
	validates :user_id, :question_id, :value, presence: true 
	validates :value, inclusion: { in: [-1,1] }
	validates_uniqueness_of :user_id, scope: :question_id 

	belongs_to :user
	belongs_to :question 
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true 

	has_many :taggings
	has_many :questions, through: :taggings
	has_many :user_tags 
	has_many :users, through: :user_tags 

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

	belongs_to :tag
	belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :password_digest, :session_token, presence: true 
	validates :password, length: { minimum: 6, allow_nil: true}
	validates :username, uniqueness: true 

	attr_reader :password

	has_many :questions
	has_many :answers
	has_many :answered_questions, through: :answers, source: :question  
	has_many :user_tags
	has_many :tags, through: :user_tags, source: :tag
	has_many :comments 
	has_many :q_upvotes,
	class_name: "QuestionUpvote",
	foreign_key: :user_id,
	primary_key: :id 

	has_many :voted_questions, through: :q_upvotes, source: :question 

	has_many :a_upvotes,
	class_name: "AnswerUpvote",
	foreign_key: :user_id,
	primary_key: :id 

	has_many :voted_answers, through: :a_upvotes, source: :answer 

	after_initialize :ensure_session_token

	def self.find_by_credentials(username, password)
		user = User.find_by(username: username)
		return nil unless user && user.valid_password?(password)
		user
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def valid_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def reset_token!
		self.session_token = SecureRandom.urlsafe_base64(16)
		self.save!
		self.session_token
	end

	private

	def ensure_session_token
		self.session_token ||= SecureRandom.urlsafe_base64(16)
	end
end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
	validates :user_id, :tag_id, presence: true 

	belongs_to :user 
	belongs_to :tag 
end

app/controllers/api/tags_controller.rb
class Api::TagsController < ApplicationController
  def index
  	@tags = Tag.all
  end

  def create 
  	if params[:user_tag]
  		@tags = []
  			UserTag.where(user_id: current_user.id).each do |tag|
  				UserTag.destroy(tag)
  			end
  		params[:user_tag][:tag_names].each do |tag_name|
  			UserTag.create(tag_id: Tag.find_by_name(tag_name).id, user_id: current_user.id ) 
  		end
  		params[:user_tag][:tag_names].each do |tag_name|
  			@tags.push(Tag.find_by_name(tag_name))
  		end

  		render :index 
  	elsif params[:tagging] 
  		params[:tagging][:tag_names].each do |tag_name|
	  		Tagging.create(tag_id: Tag.find_by_name(tag_name).id, question_id: params[:tagging][:question_id])
	  	end
	  	render json: params[:user_tag][:tag_names]
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_credentials(
			params[:user][:username],
			params[:user][:password]
		)

		if user
			sign_in(user)
			redirect_to root_url
		else
			flash.now[:errors] = ["Invalid username or password"]
			render :new
		end
	end

	def destroy
		sign_out
		render json: {}
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action  :require_login 

	def index

	end

	private

	def require_login
		unless signed_in?
			flash[:errors] = ["You must be logged in to access this section"]
			redirect_to new_session_url 
		end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in(@user)
			redirect_to root_url
		else
			flash.now[:errors] = @user.errors.full_messages
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		render :show, formats: :json 
	end

	def update
		@user = User.find(params[:id])
		if params[:user][:picture_url]
			@user.picture_url = params[:user][:picture_url]
			@user.save!
			render :show
		else 
			@user.update!(user_params)
			render :show 
		end
	end

	private

	def user_params
		params.require(:user).permit(:password, :username, :picture_url, :email, :bio, :tagline, :display_name)
	end
end

app/helpers/api/answer_upvotes_helper.rb
module Api::AnswerUpvotesHelper
end

app/helpers/api/answers_helper.rb
module Api::AnswersHelper
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/questions_helper.rb
module Api::QuestionsHelper
end

app/helpers/api/tags_helper.rb
module Api::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div id="landing" class="container sign-in">
  <h1 class="title-sign-in"> Answer.</h1>
  

<div class="sign-in-line-up"> 
  <h4 class="title-sign-in">The place to go for answers... period.</h4> 
  <button type="button" class="btn btn-primary btn-lg" id="sign-in" data-toggle="modal" data-target="#SignIn">Sign in</button>
  <button type="button" class="btn btn-primary btn-lg" id="sign-up" data-toggle="modal" data-target="#SignUp">Sign up</button>
  <form action="<%= session_url %>" method="post"> 
    <%= auth_token_input %> 
    <input type="hidden" name="user[username]" value="guest">
    <input type="hidden" name="user[password]" value="password"> 
    <button class="btn btn-primary btn-lg" id="guest-login" type="submit" value="Guest Login">Guest Login</button>
  </form> 
</div> 

  <div class="modal fade" id="SignUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content sign-up-modal">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
        </div>
        <div class="modal-body">
          <form action="<%= users_url %>" method="post">
            <%= auth_token_input %>
            <label>
              Username
              <input type="text" name="user[username]" value="">
            </label>
            <label>
              Password
              <input type="password" name="user[password]" value="">
            </label>
            <input type="submit" value="Sign Up">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="SignIn" tabindex="-1" role="dialog" aria-labelledby="sign-in">
    <div class="modal-dialog" role="document">
      <div class="modal-content sign-in-modal">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="sign-in">Sign In</h4>
        </div>
        <div class="modal-body">
          <form action="<%= session_url %>" method="post">
            <%= auth_token_input %>
            <label>
              Username
              <input type="text" name="user[username]" value="">
            </label>
            <label>
              Password
              <input type="password" name="user[password]" value="">
            </label>
            <input type="submit" value="Sign In">
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69715846-1', 'auto');
  ga('send', 'pageview');

</script>

             <!-- <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div> -->


 